# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Snyk product updates
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Keep up to date with new features, feature enhancements, and fixes for all of
  Snyk's product offerings. Contact support if you require assistance.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - add_product_updates_to_rss.py
   - build.sh
   - catalog-info.yaml
   - docs/
   - README.md
   - requirements.txt

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

theme: just-the-docs
callouts:
  note:
    color: blue
logo: "/assets/images/logo-black.png"
color_scheme: prod-updates
search_enabled: true 
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true 
  button: false 
  focus_shortcut_key: 'k'
